blog/urls.py
from django.urls import path
from .views import BlogListView, BlogCreateView, BlogUpdateView, BlogDetailView, BlogDeleteView

app_name="blog"

urlpatterns = [
    path('', BlogListView.as_view(), name="home"),
    path('create/', BlogCreateView.as_view(), name="create"),
    path('<int:pk>/', BlogDetailView.as_view(), name="detail"),
    path('<int:pk>/update/', BlogUpdateView.as_view(), name="update"),
   path('<int:pk>/delete//', BlogDeleteView.as_view(), name="delete"),
]

final/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name="home"),
    path('blog/', include('blog.urls', namespace='blog'))
]

blog/models.py
from django.db import models

class Post(models.Model):
    titulo = models.CharField(max_length=250)
    contenido = models.TextField()

    def __str__(self):
        return self.titulo
    

blog/forms.py
from django import forms

from .models import Post

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields=('titulo', 'contenido')

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View, UpdateView, DeleteView
from .forms import PostCreateForm
from .models import Post
from django.urls import reverse_lazy

class BlogListView(View):
    def get(self, request, *args, **kwargs):
        posts = Post.objects.all()
        context={
            'posts': posts
        }
        return render(request, 'blog.html', context)

class BlogCreateView(View):

    def get(self, request, *args, **kwargs):
        form=PostCreateForm()
        context={
            'form':form
        }
        return render(request, 'blog_create.html', context)
    
    def post(self, request, *args, **kwargs):
        if request.method=="POST":
            form = PostCreateForm(request.POST)
            if form.is_valid():
                titulo=form.cleaned_data.get('titulo')
                conteindo = form.cleaned_data.get('contenido')

                p, created = Post.objects.get_or_create(titulo=titulo, contenido=conteindo)
                p.save()
                return redirect('blog:home')

        context={

        }
        return render(request, 'blog_create.html', context)

class BlogDetailView(View):
    def get(self, request, pk, *args, **kwargs):
        post = get_object_or_404(Post, pk=pk)
        context={
            'post':post

        }
        return render(request, 'blog_detail.html',context)

class BlogUpdateView(UpdateView):
    model=Post
    fields=['titulo', 'contenido']
    template_name='blog_update.html'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('blog:detail', kwargs={'pk':pk})

class BlogDeleteView(DeleteView):
    model=Post
    template_name = 'blog_delete.html'
    success_url=reverse_lazy('blog:home')

final/views.py
from django.views.generic import View
from django.shortcuts import render


class HomeView(View):
    def get(self, request, *args, **kwargs):
        context={

        }
        return render(request, 'index.html', context)

blog/templates/blog.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-9x1 font-size 8rem">Lista de posteos</h1>


<br>
{%for post in posts%}
<ul>
<li>
 <h2><a href={% url 'blog:detail' post.id %}>  {{post.titulo}}</a></li></h2>
 <li><a class="inline-flex items-center px-2.5 py-1.5 border border-transparent text-x5 font-medium rounded text.indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none" href="{% url 'blog:update' post.id %}">Actualizar</a></li>
    <li> <a class="inline-flex items-center px-2.5 py-1.5 border border-transparent text-x5 font-medium rounded text.indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none" href="{% url 'blog:delete' post.id %}">Borrar</a></li>
{% endfor %}
</ul>
<br>
<a class="inline-flex items-center px-2.5 py-1.5 border border-transparent text-x5 font-medium rounded text.indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none" href="{% url 'blog:create' %}">Crear</a>

{% endblock content %}

blog/templates/blog_create.html
<form method="POST">
{% csrf_token %}
titulo{{form.titulo}}
<br>
contenido{{form.contenido}}
<button type="submit">Enviar</button>
</form>

blog/templates/blog_delete.html
<h1>Estas seguro?</h1>

<form method="POST">
    {% csrf_token %}
    {{form}}
    
    <button type="submit">Borrar</button>
    </form>

blog/templates/blog_detail.html
{{post.titulo}}
<br>
{{post.contenido}}

blog/templates/blog_update.html
<form method="POST">
{% csrf_token %}
titulo{{form.titulo}}
<br>
contenido{{form.contenido}}
<button type="submit">Actualizar</button>
</form>

final/templates/base.html
{% load tailwind_tags%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% tailwind_css%}
    
    <title>Document</title>
</head>
<body>
    {% block content %}{% endblock content %}
</body>
</html>

final/templates/index.html
{% extends 'base.html' %}

{% block content %}hola, visita  mi  <a class="text-blue-500" href="{% url 'blog:home' %}"> blog aqui </a>{% endblock content %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-grey-lightest font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>